# Generated by Django 4.2.4 on 2023-09-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0003_leadreminder_set_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidcustomer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
