# Generated by Django 4.2.4 on 2023-09-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0006_alter_paidcustomer_related_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidcustomer',
            name='related_contact',
            field=models.IntegerField(null=True),
        ),
    ]
